export const TYPES = {
  FETCH_FOOD_SEARCH_REQUEST: "FETCH_FOOD_LIST_REQUEST",
  FETCH_FOOD_SEARCH_SUCCESS: "FETCH_FOOD_LIST_SUCCESS",
  FETCH_FOOD_SEARCH_FAILURE: "FETCH_FOOD_LIST_FAILURE",
  CLEAR_FOOD_SEARCH: "CLEAR_FOOD_SEARCH",
};
